// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name sql.NullString
}

type Book struct {
	ID       int64
	Title    sql.NullString
	AuthorID sql.NullInt64
	ISBN     sql.NullString
}
