// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64          `json:"id"`
	Name sql.NullString `json:"name"`
}

type Book struct {
	ID       int64          `json:"id"`
	Title    sql.NullString `json:"title"`
	AuthorID sql.NullInt64  `json:"author_id"`
	ISBN     sql.NullString `json:"isbn"`
}
