// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	BooksByAuthor(ctx context.Context, name sql.NullString) ([]Book, error)
	CreateAuthor(ctx context.Context, name sql.NullString) (Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteAuthor(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
